# Generated by Django 4.2.3 on 2023-07-07 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_venta_administrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comentario',
            table='comentarios',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='productos',
        ),
        migrations.AlterModelTable(
            name='rol',
            table='roles',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
        migrations.AlterModelTable(
            name='usuariorol',
            table='usuarios_roles',
        ),
    ]
